version: '3.5'

services:
  front-movil:
    build:
      context: ../..
      dockerfile: ./deploy/local/Dockerfile
    volumes:
      - '../..:/app'
      - '/app/node_modules'
    tty: true
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
      - '19006:19006'
    environment:
      - API_URL=${API_URL}
    healthcheck:
      disable: true
